let contenus = [
	{ jour: 1, desc: "Grâce à votre patience et à votre dévouement, nos enfants font des apprentissages qui resteront toute leur vie! Nous sommes reconnaissants que ce soit fait avec autant d'humanité, d'humour et d'amour! Merci merci merci!"},
	{ jour: 2, desc: "Merci pour votre belle implication"},
	{ jour: 3, desc: "Merci pour toute la patience et l'amour à Liz pour cette année. Joyeux Noël et bonne année!!!"},
	{ jour: 4, desc: "Merci à vous toutes (et Mathieu :) ) pour votre excellent travail avec nos petits cocos!"},
	{ jour: 5, desc: "Merci à tous pour l'encadrement, l'attention et la tendresse que vous offrez à nos petits amours."},
	{ jour: 6, desc: "Un grand merci pour tout le travail précieux que vous faites pour faire grandir nos enfants dans un espace sécurisant et bienveillant !"},
	{ jour: 7, desc: "Un grand merci a vous de vous occupé  si bien de nos cocos, ils nous font sentir qu'ils sont bien avec vous en nous racontent  tous les beaux projets  et découvertes  qu'ils  font chaque semaines  vous êtes  precieux ne l'oublier  pas car vous faire une énorme  difference dans leur vie  mercii x0x0x"},
	{ jour: 8, desc: "Merci pour votre patience et vos sourires!"},
	{ jour: 9, desc: "Votre travail est important. Vous l'êtes d'autant plus. Merci pour tout"},
	{ jour: 10, desc: "Merci de prendre soin de notre fille et de lui montrer pleins de choses"},
	{ jour: 11, desc: "Merci pour tout l'amour que vous donnez à nos enfants !"},
	{ jour: 12, desc: "Votre travail est important et très apprécié :)"},
	{ jour: 13, desc: "Votre soutien est inestimable! On vous aime tellement! Merci!"},
	{ jour: 14, desc: "Merci pour votre dévouement!"},
	{ jour: 15, desc: "Votre dévouement et vos sourires sont précieux! Vous faites un boulot extra, merci à toute l'équipe. On est chanceux de vous avoir!"},
	{ jour: 16, desc: "Un gros merci à tous de bien prendre soin de nos amours! Votre travail est très apprécié, ne lâchez pas!!!"},
	{ jour: 17, desc: "Merci beaucoup pour vos efforts ❤️"},
	{ jour: 18, desc: "Merci d’être là au quotidien pour nos enfants"},
	{ jour: 19, desc: "Merci pour votre bon travail 🤗"},
	{ jour: 20, desc: "Merci pour votre grande générosité et votre disponibilité avec nos enfants. Ce que nous avons de plus précieux dans la vie est entre bonnes mains ! Merci beaucoup !"},
	{ jour: 21, desc: "Merci, merci, merci ! Vous êtes presque des membres de notre famille maintenant et nous nous sentons très chanceux de vous avoir à nos côtés."},
	{ jour: 22, desc: "Merci, merci, merci ! Vous êtes presque des membres de notre famille maintenant et nous nous sentons très chanceux de vous avoir à nos côtés."},
	{ jour: 23, desc: "Nous sommes très reconnaissants de l'amour et de la générosité que vous partagez avec nos enfants et avec nous. Nous tenons à vous exprimer notre profonde gratitude pour votre travail effectué avec passion et bienveillance."},
	{ jour: 24, desc: "Merci beaucoup pour votre dévouement et votre patience. Votre travail est nécessaire au bon développement de nos futurs adultes. Continuez d’inspirer nos minis!!!"},
	{ jour: 25, desc: "Un grand merci à nos educatrices pour leurs devouements aupres de nos tresors. Mes enfants expriment du plaisir à se rendre à la garderie tous les matins et je suis temoins de leurs epanouossements tous les jours"},
	{ jour: 26, desc: "Merci profondément à vous qui êtes une deuxième famille pour nos enfants! À votre dévouement de tous ces moments du quotidien, vous êtes des anges!!! Que ces temps de réjouissances illuminent vos coeurs, inspirent vos âmes et ressourcent vos êtres précieuses Éducatrices, chères Chantale, Catherine et Nathalie! Merveilleuse Équipe Vous Êtes, Joyeuses Fêtes et Vive Santé!!!"},
	
]
